### ISSUE TITLE
[Enhancement] Redirects stack up

### ISSUE THREAD

**Issue by jsayer101** [manchenkoff/nuxt-auth-sanctum#109]
**Describe the bug**
I have a login page that is protected with sanctum:guest.
I have a "/" route that is protected with sanctum:auth.
When I go to / it redirects me to /login/?redirect=/.
If I hit ctrl+R it chains redirects in the URL. If I login successfuly, it redirect to the first redirect (it deletes a redirect in the URL) but it stays on the same page. If I try to login again I got an error (as I'm already logged-in).

Stacked login/?redirect=/login/?redirect=/login/?redirect=/login/?redirect=/ doesn't redirect.

**To Reproduce**
Enable redirects
Go to a protected page, it redirects you to the login page, hit ctrl+R, try to login, it doesn't redirect you to the last redirection.

**Expected behavior**
Redirect to the protected page (and maybe doesn't stack up the redirects)

**Module information**

-   Version: 0.4.0
```typescript
sanctum: {
    mode: 'cookie',
    redirectIfAuthenticated: true,
    endpoints: {
      csrf: '/sanctum/csrf-cookie',
      login: '/login',
      logout: '/logout',
      user: '/user',
    },
    redirect: {
      keepRequestedRoute: true,
      onLogin: '/',
      onGuestOnly: '/',
      onLogout: '/login',
      onAuthOnly: '/login',
    },
  },
```

**Nuxt environment:**

-   Version: 3.12.2
-   Mode: SSR False
-   Environment: local and prod

**Laravel environment:**

-   Version: 11
-   Sanctum installed via Breeze: [x]

**Comment by jsayer101** [comment]
Edit : This behaviour seems to happens only in prod. I've tried to reproduce this on my mac in dev and it doesn't stack up

We use non-SSR.

We're using
```bash
yarn generate
```

and then Nginx to serve files.

**Comment by manchenkoff** [comment]
@jsayer101 thanks for more details. Maybe there is something related to redirects, not sure yet, can you double-check please that it also happens if instead "redirect=/login/" there will be "redirect=/login", will it also put item to the stack?

**Comment by jsayer101** [comment]
I've tried to use /login instead of /login/ and yes it does stack up

**Comment by manchenkoff** [comment]
I see @jsayer101, thanks for the confirmation. I'll try to replicate the same environment with the generated site and nginx, will keep you posted!

**Comment by jsayer101** [comment]
@manchenkoff thanks 💯

**Comment by manchenkoff** [comment]
Even with generated content and nginx I ended up with a bit different behavior. It doesn't stack up in the query param, but for some reason, it cannot keep the authentication state after refresh even if cookies are set (I need to check Nuxt docs to get a grasp on the difference between CSR and Static Generated content).

@jsayer101 could you please check if CSR mode will trigger the same behavior or is it generated-specific? It would be really helpful

**Comment by jsayer101** [comment]
Hi 👋🏼 

So I've tried to reproduce my prod bug using `npx nuxi generate` and then using `npx nuxi preview` on my computer. But it seems good, no signs of the bug.

My setup in prod is a Docker image with a `npx nuxi generate`  and with nginx serving my static files.

On top of that I have a Docker compose stack with traefik serving my container.

So I think it can either come from nginx or from Traefik but I really don't know what can I do .. Are there any configurations that needs to be done ?

**Comment by manchenkoff** [comment]
Hey @jsayer101, this is a really tricky thing now 😄 I don't have any knowledge about your nginx and traefik setup but it might be the case that URL or query string is overwritten by some rule.

It would be helpful if you can test your production Nginx setup locally with generated output from the same setup that you use in prod and if the issue persists, then provide their configs here (or Dockerfiles), so we can take a closer look

**Comment by manchenkoff** [comment]
I've just published a new version 0.4.2, please try it as well, maybe the issue will not occur @jsayer101

**Comment by jsayer101** [comment]
> I've just published a new version 0.4.2, please try it as well, maybe the issue will not occur @jsayer101

Hey ! Thanks, we're going to have a release soon (within the next days), I'll keep you posted 😄

**Comment by jsayer101** [comment]
We launched our version in prod and our problem is completed gone !

Thanks a lot 😄

**Comment by seitenumbruch** [comment]
I am currently having exactly this issue. The redirect on the login-page is stacking up.

Setup and issue are pretty much identical to what jsayer101 described:
- I am running Nuxt in no-SSR mode.
- I am only having this issue in production, not on localhost.
- I am using Nginx in production.

I am using version 0.4.4. So version 0.4.2 did not fix this issue for me.

However, I believe I have narrowed down the issue.

I compared the redirect behavior locally and in production. This is what I got, when I tried to access the auth-only route `/example` as guest:

```
localhost:8000/login?redirect=/example
production.com/login?redirect=/example/
```

Notice the trailing slash in production. It seems Nginx somehow appends a trailing slash.

Therefore, if I try to access `production.com/login` I am actually requesting `production.com/login/` from Nuxt.

So when `sanctum.global.ts` compares `path.to` with `options.redirect.onAuthOnly` they do not match (`'/login' !== '/login/'`). And so it adds a redirect*.

My Nginx-config is extremely basic and common practice. The relevant section is:

```
location / {
    try_files $uri $uri/ /index.html;
}
```

I just found out that with this configuration all requests not ending in a trailing slash will result in a `301 - Moved Permanently` pointing to the same URL *with an appended trailing slash*. [see this Stackoverflow response](https://serverfault.com/a/1094257)

To avoid this I can amend my Nginx configuration like so:

```
location / {
    try_files $uri /index.html;
}
```

Of course, this is too late for all those, who already have received a `301 - Moved Permanently`. They would have to manually remove those from their browsers.

I have yet to determine how best to configure Nginx to best meet all requirements. I am not well-versed in Nginx...

**Since `try_files $uri $uri/ /index.html;` is widely used in Nginx configs, might it be worth considering to account for trailing slashes in `nuxt-auth-sanctum`?**

*I had not (yet) configured `meta.sanctum.guestOnly: true` on the login-page, since according to the docs this shouldn't be necessary. Configuring this would prevent the redirect stack.

**Comment by manchenkoff** [comment]
Hey @seitenumbruch, thanks a lot for such detailed message! I definitely agree that slash trimming is worth adding to the module path checks, I will try to add it in a couple of days.

**Comment by jsayer101** [comment]
Hey,

I changed from middleware per page to global middleware today, and I'm experiencing the same issue I had.

Timing is perfect of you got any solution @manchenkoff 😄

**Comment by manchenkoff** [comment]
Please try to use v0.4.5, hopefully, the issue will not occur

**Comment by seitenumbruch** [comment]
I can no longer reproduce the issue.

Thank you for the quick fix!
