### ISSUE TITLE
Losing Authenticated State on Page Refresh

### ISSUE THREAD

**Issue by J0Sepff** [manchenkoff/nuxt-auth-sanctum#6]
Hello! I'm using the latest version of nuxt-auth-sanctum, but the problem of losing authorization when refreshing the page persists.

![image](https://github.com/manchenkoff/nuxt-auth-sanctum/assets/7249855/dffcf201-2ee2-45c7-85c6-ff831d2c545e)
![image](https://github.com/manchenkoff/nuxt-auth-sanctum/assets/7249855/3de5b30d-460b-4523-a2d9-1bd3554516d6)
![image](https://github.com/manchenkoff/nuxt-auth-sanctum/assets/7249855/dc31dbf7-9d28-422b-bcf5-264a37dce21e)

Nuxt config:
```
export default defineNuxtConfig({
  devtools: { enabled: false },
  css: ["assets/styles/common.scss"],
  modules: [
    "@nuxtjs/eslint-module",
    "@nuxtjs/tailwindcss",
    "@vueuse/nuxt",
    "@pinia/nuxt",
    "nuxt-swiper",
    "nuxt-auth-sanctum",
  ],
  ssr: false,
  app: {
    pageTransition: { name: "page", mode: "out-in" },
  },
});
```

Nuxt ENV:
```
NUXT_PUBLIC_SANCTUM_BASE_URL=http://10.0.1.6/api/v1
NUXT_PUBLIC_SANCTUM_ORIGIN=http://10.0.1.6:3000
NUXT_PUBLIC_SANCTUM_ENDPOINTS_CSRF=http://10.0.1.6/api/csrf-cookie
NUXT_PUBLIC_SANCTUM_ENDPOINTS_USER=/user
NUXT_PUBLIC_SANCTUM_REDIRECT_KEEP_REQUESTED_ROUTE=true
```

Laravel ENV:
```
SESSION_DOMAIN=10.0.1.6
SANCTUM_STATEFUL_DOMAINS=10.0.1.6:3000
```

If I turn on SSR, the following error appears:
![image](https://github.com/manchenkoff/nuxt-auth-sanctum/assets/7249855/38f344b0-619a-4957-9013-09f0f2fa62ab)

**Comment by manchenkoff** [comment]
Hey @J0Sepff, error is not related to the package since I do not use pinia, probably you forgot to exclude reactive values with localStorage during the hydration by using `skipHydrate(variable)`. Could you check with SSR enabled and adjusted Pinia store? 

In the meantime, I will try to setup a playground without SSR to make sure that authentication state stays the same after reload.

**Comment by J0Sepff** [comment]
@manchenkoff Thanks for the answer. You're right, the mistake with SSR is on my side. Authorization is saved if I use SSR, but if SSR: false, then authorization losing after refreshing the page. If necessary, we can contact you and show you a demo.

**Comment by manchenkoff** [comment]
Published new v0.0.11 version, @J0Sepff please try with this one, hope problem is solved

**Comment by J0Sepff** [comment]
@manchenkoff Problem solved! Thank you!

**Comment by manchenkoff** [comment]
Great! I guess it also was related to #4, thanks for the additional details @J0Sepff 👍

**Comment by jjjrmy** [comment]
I'm still having this issue where if you login and go to a guarded page, then refresh the page, it will show you the login prompt briefly before refreshing.

I am hosting this on Cloudflare Pages and have `ssr: true`

**Comment by manchenkoff** [comment]
@jjjrmy let's continue the conversation in #25 since I believe it's also related

**Comment by jjjrmy** [comment]
> @jjjrmy let's continue the conversation in #25 since I believe it's also related
This problem is unrelated to that issue.

I think specifically this is an issue with Nuxt + Cloudflare Pages hosting. I hosted the same repo on Digital Ocean App Services, and there is no issue with the login state. So makes me think it is some sort of rendering / environment issue with that hosting provider.

**Comment by alecritson** [comment]
I realise this is an old issue but wanted to share my experience with this (which I'm certain is related).

From what I can figure out is that the Cloudflare workers disable the `credentials` field, see: https://github.com/cloudflare/workers-sdk/issues/2514

What led me there was checking the server logs on nuxt admin and seeing:

```
the 'credentials' field on 'requestinitializerdict' is not implemented.
```

I tested this theory out by hosting on Vercel and everything worked straight away.

**Comment by manchenkoff** [comment]
Thanks @alecritson for the insight! I think it might save someone's day 😄

**Comment by alecritson** [comment]
Ok so just to follow up, I found this thread here: https://github.com/sindresorhus/ky/issues/366 which mentions about setting credentials to `undefined` if it's not supported.

I'm not a JS expert by any stretch but would something like this even work? (just copying from the PR related to that issue)

```javascript
const isCredentialsSupported = 'credentials' in Request.prototype;

await $fetch(config.endpoints.csrf, {
    baseURL: config.baseUrl,
    credentials: isCredentialsSupported ? 'include' : undefined,
});
```

I was trying to test myself with yarn link but I couldn't get it to play ball 😅

**Comment by manchenkoff** [comment]
@alecritson I'm not sure either 😄 For sure I can test a positive case, but I would need someone's help with testing it in the actual environment like Cloudflare. Just in case, will you be up for that?

**Comment by alecritson** [comment]
That'd be awesome if you could, I have Cloudflare pages all set up and ready to give it a spin 🙏

**Comment by manchenkoff** [comment]
Awesome, thanks! I'll try to open a PR in a next couple of days 👍

**Comment by manchenkoff** [comment]
Hey @alecritson, published new 0.4.1 version, please try it in your app

**Comment by alecritson** [comment]
Thanks @manchenkoff 

I had a little play and it certainly stopped the issue from coming up but I think it creates a new 🤔 

I tested on a Vercel deployment and Cloudflare. Same app, same domains, just switching the DNS out in Cloudflare.

Cloudflare now it doesn't set the cookies on page load, I assume because their workers don't support it so they don't get set on the server request. Going to login, even though the `csrf-cookie` endpoint is hit before `login` there is a CSRF token mismatch error.

Vercel does set them on page load and login works as expected, however, if I remove the cookies after the page load and go to login the same issue arises as Cloudflare.

<img width="686" alt="image" src="https://github.com/manchenkoff/nuxt-auth-sanctum/assets/1488016/e256a155-8ca3-479e-967d-17251d883f93">

Could it be that even though it's calling `csrf-cookie` beforehand it's not using the values set in time for the login request to happen? 🤔

**Comment by alecritson** [comment]
Yeah so the Cookie domain is `.domain.com` and if I load the page up in Vercel the cookies are set on load then I can see the XSRF token header is passed to the login...

<img width="529" alt="image" src="https://github.com/manchenkoff/nuxt-auth-sanctum/assets/1488016/d268ce48-162b-4252-9250-61fe5162bd0d">

Which logs me in fine and I can refresh the page and the state is maintained. If I then clear the cookies in dev tools and submit the login form without refreshing, the XSRF token isn't sent on the subsequent login endpoint, even after the `csrf-cookie` endpoint.

<img width="487" alt="image" src="https://github.com/manchenkoff/nuxt-auth-sanctum/assets/1488016/645f2282-03f1-469c-84b9-dca6b71b8f35">

**Comment by alecritson** [comment]
Yeah I'm not too sure because because in Cloudflare's instance the cookies are never set on page load due to credentials being disabled and it suffers from the same issue as the Vercel app.

So it seems if the cookies aren't set then on page load they never go into subsequent requests even though they do get set in the browser. But when the page is refreshed the cookies are overwritten and the app starts working as expected.

Once logged in though everything is perfect.

**Comment by manchenkoff** [comment]
Okay, I'll work on that. Thanks a lot @alecritson for your help with the debugging, I'll let you know if I find some solution to this.

**Comment by manchenkoff** [comment]
@alecritson I managed to reproduce the behavior with cleared cookies and logging in, the fix is on its way! Thanks!

**Comment by alecritson** [comment]
Thanks @manchenkoff seems like the latest release has Cloudflare working smoothly 🥳 

Thank you again for your work on getting this done!
